### ISSUE TITLE
Reason for no YAML output options?

### ISSUE THREAD

**Issue by johnSchnake** [cruise-automation/isopod#104]
I realize that part of the motivation for this project was to avoid YAML when possible.

I'm looking at potentially building a Sonobuoy plugin using isopod mainly for the convenient kube.* methods. However, there are times I'd like to be able to compare objects in their yaml form or print the raw yaml.

I see there is a "json" option instead of the protobuf default, why not also YAML? Trying to understand if it was a technical reason or not.

**Comment by cxuu** [comment]
Duplicate of https://github.com/cruise-automation/isopod/issues/62.

Have you tried `print(yaml.marshal(my_obj))`?

**Comment by johnSchnake** [comment]
Oh great, thanks. I see now it is part of your predeclared modules.

Thanks for the snippet too.
