### ISSUE TITLE
Don't crash when no VAULT_TOKEN is set

### ISSUE THREAD

**Issue by wosc** [cruise-automation/isopod#17]
As far as I understand it, the "vault" feature is optional, i.e. as long as you don't call any vault-related functions, everything is fine.

Therefore it would be nice if isopod would not crash `F1220 09:23:31.797004   11785 main.go:59] --vault_token or $VAULT_TOKEN must be set` and instead would ignore it. Currently I'm forced to `export VAULT_TOKEN=none` everywhere, which is of course doable, but a bit annoying.

**Comment by cxuu** [comment]
Thanks for the suggestion, which I think would indeed be more user-friendly. I have copied this to our internal ticket tracking system to have it prioritized, but if you have some bandwidth to hack together a PR I am more than happy to review it.
