### ISSUE TITLE
Deploying large CRD addons after Starlark conversion fails

### ISSUE THREAD

**Issue by nitishkrishna** [cruise-automation/isopod#65]
Error seen with strimzi CRDs:
```
E0713 10:47:57.945154   35592 main.go:243] addons run failed: `install' execution failed: failed addon installation: <addon: kafka-operator-crd> run failed: failed to store run state for `kafka-operator-crd' addon: ConfigMap "kafka-operator-crd-run-bs69sinjlrlom279ccm0" is invalid: []: Too long: must have at most 1048576 characters
```

**Comment by jonnylangefeld** [comment]
Adding some details here:
* etcd has [max size of 1MB](https://etcd.io/docs/v3.2.17/dev-guide/limit/#:~:text=1MB%20of,%20data.)
* every isopod run stores the current addon.ipd file as configmap for auditing. If an addon is larger than the max of 1MB, the rollout is still successful and live, but it couldn't be stored as configmap
* The error is reproducible with the following addon: `isopod generate <(curl -s https://strimzi.io/install/latest?namespace=kafka)`
