### ISSUE TITLE
match_addons should warn if no addons match

### ISSUE THREAD

**Issue by bplotnick** [cruise-automation/isopod#8]
I've hit this a few times where I use `match_addons`, but don't realize that there's an issue with the regex. It would be helpful if it could have some useful output including whether nothing matches. Another useful feature would be to have it say something like "Matched addons A, B, C".

**Comment by cxuu** [comment]
I share your experience and just opened a PR to surface the error if no addon is matched.

> Another useful feature would be to have it say something like "Matched addons A, B, C".

Isopod actually does exactly that https://github.com/cruise-automation/isopod/blob/master/pkg/runtime/runtime.go#L312.
